### ISSUE TITLE
BenRai - Because of its deviation threshold the oracle price in `PriceTierVesting` might prevent users from claiming tokens that should actually be claimable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#145]
BenRai

medium

# Because of its deviation threshold the oracle price in `PriceTierVesting` might prevent users from claiming tokens that should actually be claimable

## Summary

Most of the time the Oracle price is not the exact token price but has some deviation from it. This can result in users not being able to claim tokens that should actually be claimable 

## Vulnerability Detail

Chainlink oracles are updated in specific time intervals (heartbeat) or if the current price increases or decreases more than the deviation threshold. Heartbeat can be as long as 24 hours and deviation thresholds can be as high as 2%. This means that if the oracle price is close to a `tierPrice` and the price increases over the `tierPrice` but does not trigger the deviation threshold, tokens that should be claimable will not be claimable until the next scheduled oracle price update (assuming price stays the same). The oracle price update that can take as long as 24 hours. Since tokens can only be claimed while the oracle price is above the `tierPrice`, if the price falls below the tier price again, recipients will not be able to claim the tokens at a later point of time.   

Example:

Oracle:
 	Deviation threshold: 2%
	Heartbeat: 24 hours

Tier Price: 1 USD

The oracle is updated with a price of 0.99 USD. The price of the token increases to 1,000001 USD and the tokens of the tier should be claimable. Since the oracle price is still 0.99 USD recipients still cannot claim their tokens. This can last for up to 24 hours. If the token price goes down to 0.99 USD again before the oracle is updated there was no possibility to claim the tokens even though users expected it to be.

## Impact

Recipients cannot claim tokens that should be claimable and miss out on financial gains they could have had when claiming the tokens and selling them.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokensoft/blob/1f58ddb066ab383c416cfcbf95c9902683506e96/contracts/contracts/claim/abstract/PriceTierVesting.sol#L30-L45

## Tool used

Manual Review

## Recommendation

Use a second oracle like a Uniswap Pool as a backup to avoid such a scenario by comparing both prices

**Comment by BenRai1** [comment]
Escalate

According to the judge, the issue was excluded because `PriceTierVesting.sol` is out of scope for the contest. 
Even though `PriceTierVesting.sol` was not explicitly mentioned as in scope, deriving from the following issue in the Teller contest, (https://github.com/sherlock-audit/2023-03-teller-judging/issues/328), `PriceTierVesting.sol` is implicitly in scope because ` PriceTierVestingSale_2_0.sol` is in scope and it is inheriting from `PriceTierVesting`. This means all behaviour of `PriceTierVesting` that affects `PriceTierVestingSale_2_0` should also be in scope.

Therefore in my opinion, this issue should be considered as valid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> According to the judge, the issue was excluded because `PriceTierVesting.sol` is out of scope for the contest. 
> Even though `PriceTierVesting.sol` was not explicitly mentioned as in scope, deriving from the following issue in the Teller contest, (https://github.com/sherlock-audit/2023-03-teller-judging/issues/328), `PriceTierVesting.sol` is implicitly in scope because ` PriceTierVestingSale_2_0.sol` is in scope and it is inheriting from `PriceTierVesting`. This means all behaviour of `PriceTierVesting` that affects `PriceTierVestingSale_2_0` should also be in scope.
> 
> Therefore in my opinion, this issue should be considered as valid.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
**Regarding the scoping:**

See my comment on #64 

**Regarding the issue:**

Even if in scope i do not think this should be valid. 
IMHO the current oracle price is the one that is relevant for the users to claim the token or not.

**Comment by BenRai1** [comment]
I would politely disagree with your assessment that the oracle price is the price that should decide if the user can claim the tokens or not. 

I assume that the conditions communicated to users investing in a price tier vesting token are that if the price of the token exceeds price x than their tokens get unlocked and they can claim them. 

The price IMHO would be the market price of the token, meaning at what price can I buy the token on the open market. Because if you buy the token, you are not paying the price the oracle is giving you but the market price of the token.

Me as a user would not understand why the price of the token at the open market is above the tier price that should unlock my tokens but I am not able to claim my tokens that should be unlocked.

**Comment by hrishibhat** [comment]
@BenRai1 While this could improve the user experience for a more accurate price, i don't think this issue is a valid medium as the code works as expected given the design choice.

**Comment by BenRai1** [comment]
I guess only the sponsor can decide if this was really the intended behaviour or if a more accurate unlocking of tokens was intended. 

Considering that the tokens get locked again if the price falls below the tier price, I would assume that a more accurate price would be in the interest of the sponsor. 

Also we are talking about a deviation of up to 2% and a oracle heartbeat of up to 24 hours. (e.g the SOL/USD oracle (https://data.chain.link/ethereum/mainnet/crypto-usd/sol-usd) or the AVAX / USD oracle (https://data.chain.link/ethereum/mainnet/crypto-usd/avax-usd). For a token price of 200 USD (previously reached by SOL) this means a deviation of close to 4 USD without triggering a price update. 

If the price of the token stays clearly over tier price, let say at 203 USD, for a whole day and none of the investors can claim their tokens, I guess that this would not be in the interest of the protocol owner.

**Comment by cr-walker** [comment]
I don't see this as a valid issue. It would be nice to have multiple oracles but this isn't necessary for the intended use case.

**Comment by BenRai1** [comment]
Thanks for your feedback! Then the last escalation is resolved and everybody will be happy to have the final results :)

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a valid low based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/145/#issuecomment-1667746066): rejected
