### ISSUE TITLE
Yuki - Re-initializing the beneficiary if the total has been updated doesn't mint any additional voting power to the beneficiary.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#179]
Yuki

high

# Re-initializing the beneficiary if the total has been updated doesn't mint any additional voting power to the beneficiary.

## Summary
Re-initializing the beneficiary if the total has been updated doesn't mint any additional voting power to the beneficiary.

## Vulnerability Detail
When executing a claim, the function re-initialize the beneficiary if the total has been updated, since the last time the beneficiary was initialized.
- The problem here is that the function initializes the benificary, but doesn't actually mint any additional voting power to it.

```solidity
  function _executeClaim(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual returns (uint256) {
    uint120 totalAmount = uint120(_totalAmount);

    // effects
    if (records[beneficiary].total != totalAmount) {
      // re-initialize if the total has been updated
      _initializeDistributionRecord(beneficiary, totalAmount);
    }
    
    uint120 claimableAmount = uint120(getClaimableAmount(beneficiary));
    require(claimableAmount > 0, 'Distributor: no more tokens claimable right now');

    records[beneficiary].claimed += claimableAmount;
    claimed += claimableAmount;

    return claimableAmount;
  }
```
```solidity
  function _initializeDistributionRecord(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual {
    uint120 totalAmount = uint120(_totalAmount);

    // Checks
    require(totalAmount <= type(uint120).max, 'Distributor: totalAmount > type(uint120).max');

    // Effects - note that the existing claimed quantity is re-used during re-initialization
    records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);
    emit InitializeDistributionRecord(beneficiary, totalAmount);
  }
```
For example, take the PriceTierVestingSale_2_0 contract.
- The total depends on the purchased amount by the beneficiary.
- If the beneficiary purchase more tokens, his purchased amount increases.
- The beneficiary calls the claim function.
- The claim function will re-initalize his beneficiary to the current purchased amount but won't mint the additional voting power earned by the beneficiary depending on how much more tokens the beneficiary purchased.

## Impact
Loss of voting power duo to the contract initializing the beneficiary without minting any additional voting power to it.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L66

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L47

## Tool used

Manual Review

## Recommendation
Hard to do a fix here as a lot of vesting contracts depend on the Distributor contract, and few of them have different logic. 

- E.g. the BasicDistributor contract doesn't have this issue, as the total is adjusted by the owner.

**Comment by ghost** [comment]
Escalate 

This should be a valid issue:

1. When the claim function is called, it has a feature to re-initialize the beneficiary depending on how much the total amount changed since the last time it was initialized. 
2. However this feature only updates the DistributionRecord struct, but doesn't mint or burn additional voting power to the beneficiary depending how much the total amount changed from the last initialization.
3. Which results in a loss of voting power for the user.

You can see by the sponsor's fix on issue #41, which affects the function `initializeDistributionRecord`, that additional voting power is going to be burned or minted from/to the beneficiary depending on his current total amount.

https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/41#issuecomment-1656399673

The issue in the `claim` function is that it can re-initialize the beneficiary's distribution record, but doesn't actually mint/burn additional voting power to/from it. As the internal function `_initializeDistributionRecord` is called which only updates the Distribution record struct.

```solidity
  function _executeClaim(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual returns (uint256) {
    uint120 totalAmount = uint120(_totalAmount);

    // effects
    if (records[beneficiary].total != totalAmount) {
      // re-initialize if the total has been updated
      _initializeDistributionRecord(beneficiary, totalAmount);
    }
    
    uint120 claimableAmount = uint120(getClaimableAmount(beneficiary));
    require(claimableAmount > 0, 'Distributor: no more tokens claimable right now');

    records[beneficiary].claimed += claimableAmount;
    claimed += claimableAmount;

    return claimableAmount;
  }
``` 
```solidity
  function _initializeDistributionRecord(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual {
    uint120 totalAmount = uint120(_totalAmount);

    // Checks
    require(totalAmount <= type(uint120).max, 'Distributor: totalAmount > type(uint120).max');

    // Effects - note that the existing claimed quantity is re-used during re-initialization
    records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);
    emit InitializeDistributionRecord(beneficiary, totalAmount);
  }
```

### Conclusion

1. Beneficiaries which increased their purchase amount are going to lose their additional voting power when they call the function `claim`. As the function will re-initialize only the DistributionRecord of the beneficiary without minting the additional voting power to it.
2. Malicious beneficiaries can abuse this issue in order to keep their voting power when their purchase amount is lesser than their last initialization, they can call `claim` and the function will re-initialize the beneficiary's DistributionRecord without burning the needed voting power from it. As a result a beneficiary can have more voting power than the amount he purchased.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This should be a valid issue:
> 
> 1. When the claim function is called, it has a feature to re-initialize the beneficiary depending on how much the total amount changed since the last time it was initialized. 
> 2. However this feature only updates the DistributionRecord struct, but doesn't mint or burn additional voting power to the beneficiary depending how much the total amount changed from the last initialization.
> 3. Which results in a loss of voting power for the user.
> 
> You can see by the sponsor's fix on issue #41, which affects the function `initializeDistributionRecord`, that additional voting power is going to be burned or minted from/to the beneficiary depending on his current total amount.
> 
> https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/41#issuecomment-1656399673
> 
> The issue in the `claim` function is that it can re-initialize the beneficiary's distribution record, but doesn't actually mint/burn additional voting power to/from it. As the internal function `_initializeDistributionRecord` is called which only updates the Distribution record struct.
> 
> ```solidity
>   function _executeClaim(
>     address beneficiary,
>     uint256 _totalAmount
>   ) internal virtual returns (uint256) {
>     uint120 totalAmount = uint120(_totalAmount);
> 
>     // effects
>     if (records[beneficiary].total != totalAmount) {
>       // re-initialize if the total has been updated
>       _initializeDistributionRecord(beneficiary, totalAmount);
>     }
>     
>     uint120 claimableAmount = uint120(getClaimableAmount(beneficiary));
>     require(claimableAmount > 0, 'Distributor: no more tokens claimable right now');
> 
>     records[beneficiary].claimed += claimableAmount;
>     claimed += claimableAmount;
> 
>     return claimableAmount;
>   }
> ``` 
> ```solidity
>   function _initializeDistributionRecord(
>     address beneficiary,
>     uint256 _totalAmount
>   ) internal virtual {
>     uint120 totalAmount = uint120(_totalAmount);
> 
>     // Checks
>     require(totalAmount <= type(uint120).max, 'Distributor: totalAmount > type(uint120).max');
> 
>     // Effects - note that the existing claimed quantity is re-used during re-initialization
>     records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);
>     emit InitializeDistributionRecord(beneficiary, totalAmount);
>   }
> ```
> 
> ### Conclusion
> 
> 1. Beneficiaries which increased their purchase amount are going to lose their additional voting power when they call the function `claim`. As the function will re-initialize only the DistributionRecord of the beneficiary without minting the additional voting power to it.
> 2. Malicious beneficiaries can abuse this issue in order to keep their voting power when their purchase amount is lesser than their last initialization, they can call `claim` and the function will re-initialize the beneficiary's DistributionRecord without burning the needed voting power from it. As a result a beneficiary can have more voting power than the amount he purchased.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Hey @cr-walker. l believe this finding was missed and need to be fixed. 

Reference: https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/179#issuecomment-1669407093

**Comment by jkoppel** [comment]
It looks to me like the intended use is that the beneficiary calls `initializeDistributionRecord` when they want their extra voting tokens. That's how it works for everything else. Where does it say that `claim` is supposed to have all the same effects as `initializeDistributionRecord`?

**Comment by ghost** [comment]
> It looks to me like the intended use is that the beneficiary calls `initializeDistributionRecord` when they want their extra voting tokens. That's how it works for everything else. Where does it say that `claim` is supposed to have all the same effects as `initializeDistributionRecord`?

l don't think you understand the issue here, lets wait for the sponsor and sherlock before you say what is intended and what's not.

**Comment by Shogoki** [comment]
Hmm. I am not sure about this one. 
I think it is the case, that if the total did change the record has to reinitialized, by calling `initializeDistributionRecord`. 
@cr-walker What do you think about this one?

**Comment by ghost** [comment]
> Hmm. I am not sure about this one. I think it is the case, that if the total did change the record has to reinitialized, by calling `initializeDistributionRecord`. @cr-walker What do you think about this one?

Further information by the sponsor will be helpful.

But considering the below comment is the case then the function claim wouldn't have the re-initialize feature.

`that if the total did change the record has to reinitialized, by calling initializeDistributionRecord.`

**Comment by cr-walker** [comment]
Here's the intended behavior:

When initializing a distribution record or claiming tokens from an `AdvancedDistributor` voting power should be updated correctly.

We saw a couple similar issues (https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/14, https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/41).

But I don't think the specific issue highlighted here is correct because contracts like the `PriceTierVestingSale_2_0` distributor inherit `AbstractDistributor` which does increment voting power.

```
  function _initializeDistributionRecord(
    address beneficiary,
    uint256 totalAmount
  ) internal virtual override {
    super._initializeDistributionRecord(beneficiary, totalAmount);

    // add voting power through ERC20Votes extension
    _mint(beneficiary, tokensToVotes(totalAmount));
  }
  ```
  
  Note that the logic above is *wrong* as highlighted in the other issues, but at least it's there. @SilentYuki's - did you miss that override? It's late so I might be missing something too: if you have a unit test demonstrating the behavior I might be persuaded but I don't think the bug is present as described due to the above code in `AdvancedDistributor`.

**Comment by ghost** [comment]
The mistake was on my side, didn't see the override function and thought the function `_initializeDistributionRecord` in BasicDistributor is called instead.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SilentYuki](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/179/#issuecomment-1669407093): rejected
